<a href="https://colab.research.google.com/github/amarviswanathan/AppliedDataScience/blob/master/pytorchnlp/pytorchbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
def describe(x):

  print(f"Type: {x.type()}")
  print(f"Shape/Size: {x.shape}")
  print(f"Values: {x}")

In [4]:
describe(torch.Tensor(2,3))

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: tensor([[-4.8900e-34,  3.0750e-41,  3.7835e-44],
        [ 0.0000e+00,         nan,  6.4460e-44]])


In [5]:
describe(torch.rand(2,3))  # uniform random
describe(torch.randn(2,3)) # random normal

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: tensor([[0.6742, 0.1788, 0.1003],
        [0.4605, 0.5115, 0.4904]])
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: tensor([[-0.4851,  0.4266, -0.3113],
        [ 1.6293, -1.5889, -0.8707]])


In [8]:
# We can also create tensors with specified values using the fill_ method. Anything with '_' means that content is modified in place

x1 = torch.ones(2,3)  # filled with ones
describe(x1)
x1.fill_(5)   # filled with 5
describe(x1)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [9]:
# Using lists to create tensors

x = torch.Tensor([[1,2,3],[4,5,6]])
describe(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [10]:
# Creating and initializing arrays from numpy
import numpy as np

In [11]:
npy = np.random.rand(2,3)
describe(torch.from_numpy(npy))

Type: torch.DoubleTensor
Shape/Size: torch.Size([2, 3])
Values: tensor([[0.6893, 0.0716, 0.9813],
        [0.1648, 0.5101, 0.2870]], dtype=torch.float64)


In [12]:
# Dimension based operations


x = torch.arange(6)
describe(x)

Type: torch.LongTensor
Shape/Size: torch.Size([6])
Values: tensor([0, 1, 2, 3, 4, 5])


In [13]:
x = x.view(2,3)
describe(x)

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: tensor([[0, 1, 2],
        [3, 4, 5]])


In [14]:
# dim = 0 implies row wise addition
describe(torch.sum(x,dim=0))

Type: torch.LongTensor
Shape/Size: torch.Size([3])
Values: tensor([3, 5, 7])


In [15]:
# dim = 1 implies column wise addition
describe(torch.sum(x,dim=1))

Type: torch.LongTensor
Shape/Size: torch.Size([2])
Values: tensor([ 3, 12])


In [16]:
describe(torch.transpose(x,0,1)) # Find another way to transpose

Type: torch.LongTensor
Shape/Size: torch.Size([3, 2])
Values: tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [17]:
import torch

x = torch.arange(6).view(2,3)
describe(x)

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: tensor([[0, 1, 2],
        [3, 4, 5]])


In [21]:
# start:end:step,  start index included, end index excluded 
x[:1,:2]

tensor([[0, 1]])

In [22]:
# Non contiguous indexing

indices = torch.LongTensor([0,2])
indices

tensor([0, 2])

In [24]:
torch.index_select(x,dim=1,index=indices)

tensor([[0, 2],
        [3, 5]])